LoginGmail/LoginGmail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('social_django.urls', namespace='social')),
]

LoginGmail/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),

]

LoginGmail/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=11)

LoginGmail/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('phone_number', )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields


class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=50)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    phone_number = forms.CharField(max_length=11)


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)

LoginGmail/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib import messages
from .models import CustomUser
from django.contrib.auth import authenticate, login, logout



class HomeView(View):

    def get(self, request):
        return render(request, 'accounts/home.html')


class UserRegisterView(View):
    def get(self, request):
        form = UserRegistrationForm
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            CustomUser.objects.create_user(**cd)
            messages.success(request, 'You Registered Successfully', 'success')
            return redirect('accounts:home')
        return render(request, 'accounts/register.html', {'form': form})


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'Logged in Successfully', 'success')
                return redirect('accounts:home')
            messages.error(request, 'Username or Password is Wrong', 'danger')
            return render(request, 'accounts/login.html', {'form': form})


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'Logged out Successfully', 'success')
        return redirect('accounts:home')

LoginGmail/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    Home
{% endblock %}

LoginGmail/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Login User {% endblock %}


{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>

{% endblock %}

LoginGmail/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}
{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

LoginGmail/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{%endblock%}</title>
<!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></head>
<body>
        {% include 'inc/messages.html' %}
        {% include 'inc/navbar.html' %}
        {%  block content %}  {%  endblock %}

</body>
</html>

LoginGmail/templates/inc/messages.html
{% if messages %}

    {% for msg in messages%}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}

{% endif %}

LoginGmail/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

      <div class="navbar-nav">
          <br>
        {% if request.user.is_authenticated %}
             <p style="color:red">Hi : {{ user.username }}</p>
             <a class="nav-link active"  href="{% url 'accounts:user_logout' %}">Logout</a>
        {% else %}
             <a class="nav-link active"  href="{% url 'accounts:user_register' %}">Register</a>
             <a class="nav-link active"  href="{% url 'accounts:user_login' %}">Login</a>
             <a class="btn btn-info" aria-current="page" href="{% url 'social:begin' 'google-oauth2' %}">Login/Signup With Google</a>
        {% endif %}
      </div>
  </div>
</nav>